/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Return the health status of the service and its dependencies.
         *
         *     Responds with 503 when any dependency is down.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/songs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Songs
         * @description List the playable songs, searching title and artist with ``q``.
         */
        get: operations["list_songs_songs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/songs/{song_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Song
         * @description Get a playable song with its synced lyrics (without the pitch curve).
         */
        get: operations["get_song_songs__song_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/songs/{song_id}/instrumental": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Instrumental
         * @description Stream the karaoke track, supporting HTTP range requests (seeking).
         */
        get: operations["stream_instrumental_songs__song_id__instrumental_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/songs/{song_id}/pitch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pitch
         * @description Get the reference pitch of a song, or of one line with ``line``.
         */
        get: operations["get_pitch_songs__song_id__pitch_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Session
         * @description Start singing a song; scoring is bound to its current analysis.
         */
        post: operations["create_session_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session Results
         * @description Report a session: totals and the result of every line.
         */
        get: operations["get_session_results_sessions__session_id__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/lines/{line_index}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Line Analysis
         * @description How one line was sung: reference vs sung curves, offsets and score.
         */
        get: operations["get_line_analysis_sessions__session_id__lines__line_index__analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/songs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Song
         * @description Upload a song and queue it for processing.
         *
         *     ``separation_preset`` is ``demucs`` or ``roformer``; empty means the
         *     server default. ``lyrics`` are the official lyrics, one verse per line.
         */
        post: operations["upload_song_admin_songs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/songs/{song_id}/lyrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Song Lyrics
         * @description Set the official lyrics of a song (one verse per line).
         *
         *     They are used the next time the song's lines are built.
         */
        put: operations["set_song_lyrics_admin_songs__song_id__lyrics_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/songs/{song_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Song Status
         * @description Report the status of a song and of its latest ingestion job.
         */
        get: operations["get_song_status_admin_songs__song_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/sessions/{session_id}/lines/{line_index}/debug": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Line Diagnostics
         * @description Everything behind a line score: raw inputs, parameters and word timing.
         */
        get: operations["get_line_diagnostics_admin_sessions__session_id__lines__line_index__debug_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_song_admin_songs_post */
        Body_upload_song_admin_songs_post: {
            /** File */
            file: string;
            /** Title */
            title: string;
            /** Artist */
            artist: string;
            /** Language */
            language?: string | null;
            /** Separation Preset */
            separation_preset?: string | null;
            /** Lyrics */
            lyrics?: string | null;
        };
        /**
         * Difficulty
         * @description How far from the note singing still earns credit.
         *
         *     Attributes:
         *         EASY: Full credit within 1 semitone, none from 3.
         *         NORMAL: Full credit within 3/4 of a semitone, none from 2.5.
         *         HARD: Full credit within half a semitone, none from 2.
         * @enum {string}
         */
        Difficulty: "easy" | "normal" | "hard";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Overall service health status.
         *
         *     Attributes:
         *         status: ``"ok"`` when every dependency is up, ``"degraded"`` otherwise.
         *         checks: Status of each external dependency, keyed by its name.
         */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Checks */
            checks: {
                [key: string]: "up" | "down";
            };
        };
        /**
         * IngestionStage
         * @description Current stage of an ingestion job.
         * @enum {string}
         */
        IngestionStage: "queued" | "separating" | "transcribing" | "segmenting" | "extracting_pitch" | "persisting" | "done" | "failed";
        /**
         * JobReport
         * @description State of an ingestion job.
         *
         *     Attributes:
         *         id: Job id.
         *         stage: Current or final stage.
         *         task_id: Id of the queued task, if it was queued.
         *         error_message: Failure reason, if it failed.
         *         created_at: When the job was created.
         *         started_at: When processing started.
         *         finished_at: When it finished, successfully or not.
         */
        JobReport: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            stage: components["schemas"]["IngestionStage"];
            /** Task Id */
            task_id: string | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /**
         * LineAnalysis
         * @description A sung line explained frame by frame, on the scoring timeline.
         *
         *     Every list has one value per scoring frame from the line start; None marks
         *     frames without voice (or without a value).
         *
         *     Attributes:
         *         result: The line score, identical to ``score_line``.
         *         hop_ms: Time between frames.
         *         reference_midi: Reference pitch.
         *         reference_weight: Confidence weight of each reference frame (0-1).
         *         sung_midi: What was sung at each moment (latency undone), shifted by
         *             whole octaves to the reference's register (``octave_shift``).
         *         aligned_midi: For each sung reference frame, the sung pitch DTW
         *             matched to it, in the reference's octave: what was scored.
         *         credit: Credit (0-1) of each sung reference frame.
         *         alignment_path: Pairs ``[reference_frame, sung_frame]`` of the
         *             alignment path.
         *         octave_shift: Whole octaves (in semitones) removed from ``sung_midi``,
         *             e.g. -12 when the line was sung an octave lower.
         *         timing_offset_ms: Median delay of the matched sung frames (positive:
         *             sung late), None if nothing was matched.
         *         pitch_offset_semitones: Median pitch error with sign (positive: sharp),
         *             None if nothing was matched.
         */
        LineAnalysis: {
            result: components["schemas"]["LineResult"];
            /** Hop Ms */
            hop_ms: number;
            /** Reference Midi */
            reference_midi: (number | null)[];
            /** Reference Weight */
            reference_weight: number[];
            /** Sung Midi */
            sung_midi: (number | null)[];
            /** Aligned Midi */
            aligned_midi: (number | null)[];
            /** Credit */
            credit: (number | null)[];
            /** Alignment Path */
            alignment_path: [
                number,
                number
            ][];
            /** Octave Shift */
            octave_shift: number;
            /** Timing Offset Ms */
            timing_offset_ms: number | null;
            /** Pitch Offset Semitones */
            pitch_offset_semitones: number | null;
        };
        /**
         * LineDiagnostics
         * @description Everything behind a line score, for admins debugging sync and scoring.
         *
         *     Attributes:
         *         latency_ms: Latency compensated for the session.
         *         scoring: Exact scoring parameters used (difficulty included).
         *         analysis_version: Version of the song analysis the session uses.
         *         pipeline: Models that produced that analysis.
         *         reference: Reference pitch of the line at its native resolution
         *             (frame 0 at ``start_ms``).
         *         sung_input: Pitch exactly as the client sent it, None if not stored.
         *         word_timing: Words with their voicing and transcriber confidence.
         */
        LineDiagnostics: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Line Index */
            line_index: number;
            /** Text */
            text: string;
            /** Start Ms */
            start_ms: number;
            /** End Ms */
            end_ms: number;
            difficulty: components["schemas"]["Difficulty"];
            /** Words */
            words: components["schemas"]["PracticeWord"][];
            /**
             * Status
             * @enum {string}
             */
            status: "analyzed" | "not_sung" | "not_stored";
            analysis: components["schemas"]["LineAnalysis"] | null;
            /** Latency Ms */
            latency_ms: number;
            scoring: components["schemas"]["ScoringConfig"];
            /** Analysis Version */
            analysis_version: number;
            pipeline: components["schemas"]["PipelineInfo"];
            reference: components["schemas"]["PitchCurve"];
            sung_input: components["schemas"]["SungPitch"] | null;
            /** Word Timing */
            word_timing: components["schemas"]["WordDiagnostics"][];
        };
        /**
         * LinePractice
         * @description How the player sang one line, for the practice chart.
         *
         *     Attributes:
         *         session_id: Session.
         *         line_index: Line.
         *         text: Line text.
         *         start_ms: Line start in the song.
         *         end_ms: Line end in the song.
         *         difficulty: Pitch tolerance the line was scored with.
         *         words: Words of the line.
         *         status: Whether there is an analysis (see ``AnalysisStatus``).
         *         analysis: Curves, alignment and offsets; None unless ``analyzed``.
         */
        LinePractice: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Line Index */
            line_index: number;
            /** Text */
            text: string;
            /** Start Ms */
            start_ms: number;
            /** End Ms */
            end_ms: number;
            difficulty: components["schemas"]["Difficulty"];
            /** Words */
            words: components["schemas"]["PracticeWord"][];
            /**
             * Status
             * @enum {string}
             */
            status: "analyzed" | "not_sung" | "not_stored";
            analysis: components["schemas"]["LineAnalysis"] | null;
        };
        /**
         * LineReport
         * @description Result of one lyric line in a session report.
         *
         *     Attributes:
         *         line_index: Line index.
         *         text: Line text.
         *         sung: Whether the player sang it (unsung lines score 0 at finish).
         *         scorable: Whether the line has enough singing to be judged.
         *         score: 0-100, None if not sung yet or not scorable.
         *         accuracy: 0-1, None if not sung yet or not scorable.
         *         hit: Whether the line was a hit.
         */
        LineReport: {
            /** Line Index */
            line_index: number;
            /** Text */
            text: string;
            /** Sung */
            sung: boolean;
            /** Scorable */
            scorable: boolean | null;
            /** Score */
            score: number | null;
            /** Accuracy */
            accuracy: number | null;
            /** Hit */
            hit: boolean;
        };
        /**
         * LineResult
         * @description Score of one sung line.
         *
         *     Attributes:
         *         scorable: False when the reference has too little singing to judge.
         *         score: Weighted pitch score in [0, 100], None if not scorable.
         *         accuracy: Fraction of reference frames sung within full credit, in
         *             [0, 1], None if not scorable.
         *         hit: Whether the score reaches the hit threshold.
         *         voiced_frames: Sung reference frames, used to weight session totals.
         */
        LineResult: {
            /** Scorable */
            scorable: boolean;
            /** Score */
            score: number | null;
            /** Accuracy */
            accuracy: number | null;
            /** Hit */
            hit: boolean;
            /** Voiced Frames */
            voiced_frames: number;
        };
        /**
         * LyricLine
         * @description A line (verse) of lyrics, the unit that gets scored.
         *
         *     Attributes:
         *         index: Zero-based position of the line in the song.
         *         start_ms: Start time of the line.
         *         end_ms: End time (exclusive) of the line.
         *         text: Full text of the line as displayed.
         *         words: Words of the line, in order and without overlaps.
         */
        LyricLine: {
            /** Index */
            index: number;
            /** Start Ms */
            start_ms: number;
            /** End Ms */
            end_ms: number;
            /** Text */
            text: string;
            /** Words */
            words: components["schemas"]["Word"][];
        };
        /**
         * LyricsSummary
         * @description Result of saving the lyrics of a song.
         *
         *     Attributes:
         *         song_id: Id of the song.
         *         lines: Number of sung lines found in the lyrics.
         */
        LyricsSummary: {
            /**
             * Song Id
             * Format: uuid
             */
            song_id: string;
            /** Lines */
            lines: number;
        };
        /**
         * LyricsUpdate
         * @description Official lyrics submitted for a song.
         *
         *     Attributes:
         *         lyrics: Plain text, one verse per line. Empty lines, ``[Section]``
         *             labels and lines fully in parentheses are ignored.
         */
        LyricsUpdate: {
            /** Lyrics */
            lyrics: string;
        };
        /**
         * PipelineInfo
         * @description Models and parameters that produced the analysis, for reproducibility.
         *
         *     Attributes:
         *         separator: Source separation model (e.g. ``htdemucs``).
         *         transcriber: Speech recognition model (e.g. ``whisper-large-v3-turbo``).
         *         pitch_extractor: Pitch model (e.g. ``torchcrepe-full``).
         *         language: Language detected or forced during transcription.
         */
        PipelineInfo: {
            /** Separator */
            separator: string;
            /** Transcriber */
            transcriber: string;
            /** Pitch Extractor */
            pitch_extractor: string;
            /** Language */
            language?: string | null;
        };
        /**
         * PitchCurve
         * @description Pitch track sampled every ``hop_ms``; frame ``i`` is centered at ``i * hop_ms``.
         *
         *     Every frame keeps its pitch estimate and confidence, so the voicing decision
         *     (which frames count as singing) is made when reading, not when storing.
         *
         *     Attributes:
         *         hop_ms: Time between consecutive frames.
         *         midi: Pitch per frame as fractional MIDI note number (69.0 = A4 =
         *             440 Hz), rounded to 0.01 (1 cent); None when there is no estimate.
         *         confidence: Voicing confidence per frame, as an integer in [0, 100].
         */
        PitchCurve: {
            /** Hop Ms */
            hop_ms: number;
            /** Midi */
            midi: (number | null)[];
            /** Confidence */
            confidence: number[];
        };
        /**
         * PitchResponse
         * @description Reference pitch of a song, or of one of its lines.
         *
         *     Attributes:
         *         analysis_id: Id of the analysis the curve belongs to.
         *         line_index: The requested line, or None for the whole song.
         *         start_ms: Time of the first frame returned.
         *         hop_ms: Time between frames.
         *         midi: Pitch per frame as fractional MIDI note; None without estimate.
         *         confidence: Voicing confidence per frame, 0-100.
         */
        PitchResponse: {
            /**
             * Analysis Id
             * Format: uuid
             */
            analysis_id: string;
            /** Line Index */
            line_index: number | null;
            /** Start Ms */
            start_ms: number;
            /** Hop Ms */
            hop_ms: number;
            /** Midi */
            midi: (number | null)[];
            /** Confidence */
            confidence: number[];
        };
        /**
         * PlaySessionStatus
         * @description Lifecycle of a karaoke play session.
         * @enum {string}
         */
        PlaySessionStatus: "active" | "finished";
        /**
         * PracticeWord
         * @description A lyric word, timed from the line start.
         *
         *     Attributes:
         *         text: Word as displayed.
         *         start_ms: Start, relative to the line start.
         *         end_ms: End, relative to the line start.
         */
        PracticeWord: {
            /** Text */
            text: string;
            /** Start Ms */
            start_ms: number;
            /** End Ms */
            end_ms: number;
        };
        /**
         * ScoringConfig
         * @description Tunable parameters of line scoring.
         *
         *     Attributes:
         *         scoring_hop_ms: Frame period used to compare curves. Notes last at
         *             least ~100 ms, so 20 ms loses nothing for intonation and keeps DTW
         *             fast enough for real-time feedback.
         *         min_reference_confidence: Reference frames below this confidence
         *             (0-100) are not sung and not scored.
         *         min_voiced_ms: Lines with less sung reference than this (e.g. spoken
         *             passages) are not scorable.
         *         full_credit_semitones: Errors up to this get full credit (0.5 = 50
         *             cents, a quarter tone).
         *         zero_credit_semitones: Errors from this up get no credit; credit
         *             decreases linearly in between.
         *         max_error_semitones: Cap of the frame error; also the cost of a sung
         *             frame without voice.
         *         octave_invariant: Whether singing an octave above or below is right.
         *         max_warp_ms: How far (in time) the alignment may drift from the
         *             diagonal: enough to enter late or hold a note, not enough to match
         *             a neighboring note (None for no limit).
         *         step_penalty_semitones: Cost of each non-diagonal alignment step. It
         *             stops DTW from "rewarding" off-key singing by matching it to other
         *             reference notes of the same height (without it, singing 1.5
         *             semitones off scores 58 instead of 33). 2.0 gives the theoretical
         *             scores for detuned singing while keeping late entries (150 ms ->
         *             100) and rhythm variations (+-100 ms -> ~97) almost unpenalized.
         *         hit_threshold: Line score from which the line counts as a hit.
         */
        ScoringConfig: {
            /**
             * Scoring Hop Ms
             * @default 20
             */
            scoring_hop_ms: number;
            /**
             * Min Reference Confidence
             * @default 50
             */
            min_reference_confidence: number;
            /**
             * Min Voiced Ms
             * @default 200
             */
            min_voiced_ms: number;
            /**
             * Full Credit Semitones
             * @default 0.5
             */
            full_credit_semitones: number;
            /**
             * Zero Credit Semitones
             * @default 2
             */
            zero_credit_semitones: number;
            /**
             * Max Error Semitones
             * @default 6
             */
            max_error_semitones: number;
            /**
             * Octave Invariant
             * @default true
             */
            octave_invariant: boolean;
            /**
             * Max Warp Ms
             * @default 200
             */
            max_warp_ms: number | null;
            /**
             * Step Penalty Semitones
             * @default 2
             */
            step_penalty_semitones: number;
            /**
             * Hit Threshold
             * @default 60
             */
            hit_threshold: number;
        };
        /**
         * SeparationPreset
         * @description Source separation configuration chosen for a song.
         *
         *     Attributes:
         *         DEMUCS: Demucs ``htdemucs`` with several shifts. Fast, light on VRAM.
         *         ROFORMER: BS-RoFormer model (audio-separator). Several times slower and
         *             heavier on VRAM, but cleaner on some songs.
         * @enum {string}
         */
        SeparationPreset: "demucs" | "roformer";
        /**
         * SessionCreate
         * @description Request to start singing a song.
         *
         *     Attributes:
         *         song_id: Song to sing (must be playable).
         *         player_name: Display name of the anonymous player.
         *         latency_offset_ms: Audio latency measured by the client's calibration;
         *             positive when the voice arrives late.
         *         difficulty: Pitch tolerance of the scoring.
         */
        SessionCreate: {
            /**
             * Song Id
             * Format: uuid
             */
            song_id: string;
            /** Player Name */
            player_name: string;
            /**
             * Latency Offset Ms
             * @default 0
             */
            latency_offset_ms: number;
            /** @default normal */
            difficulty: components["schemas"]["Difficulty"];
        };
        /**
         * SessionCreated
         * @description A started play session.
         *
         *     Attributes:
         *         session_id: Id of the session (used by the WebSocket).
         *         song_id: Song being sung.
         *         analysis_id: Analysis version the session is scored against.
         *         analysis_version: Version number of that analysis.
         *         line_count: Number of lyric lines to sing.
         *         player_name: Display name of the player.
         *         latency_offset_ms: Latency applied when scoring.
         *         difficulty: Pitch tolerance of the scoring.
         */
        SessionCreated: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Song Id
             * Format: uuid
             */
            song_id: string;
            /**
             * Analysis Id
             * Format: uuid
             */
            analysis_id: string;
            /** Analysis Version */
            analysis_version: number;
            /** Line Count */
            line_count: number;
            /** Player Name */
            player_name: string;
            /** Latency Offset Ms */
            latency_offset_ms: number;
            difficulty: components["schemas"]["Difficulty"];
        };
        /**
         * SessionResults
         * @description Report of a play session.
         *
         *     Attributes:
         *         session_id: Session id.
         *         song_id: Song sung.
         *         analysis_id: Analysis the session was scored against.
         *         player_name: Display name of the player.
         *         difficulty: Pitch tolerance the session is scored with.
         *         status: ``active`` or ``finished``.
         *         started_at: When the session started.
         *         finished_at: When it finished, if it did.
         *         totals: Totals over the lines scored so far (all lines once finished).
         *         lines: One entry per lyric line, in order.
         */
        SessionResults: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Song Id
             * Format: uuid
             */
            song_id: string;
            /**
             * Analysis Id
             * Format: uuid
             */
            analysis_id: string;
            /** Player Name */
            player_name: string;
            difficulty: components["schemas"]["Difficulty"];
            status: components["schemas"]["PlaySessionStatus"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at: string | null;
            totals: components["schemas"]["SessionTotals"];
            /** Lines */
            lines: components["schemas"]["LineReport"][];
        };
        /**
         * SessionTotals
         * @description Totals of a performance.
         *
         *     Attributes:
         *         total_score: 0-100 weighted by line length; None if nothing scorable.
         *         accuracy: Fraction of in-tune frames; None if nothing scorable.
         *         best_streak: Longest run of consecutive hit lines.
         *         scored_lines: Scorable lines included.
         *         hit_lines: Lines that were hits.
         */
        SessionTotals: {
            /** Total Score */
            total_score: number | null;
            /** Accuracy */
            accuracy: number | null;
            /** Best Streak */
            best_streak: number;
            /** Scored Lines */
            scored_lines: number;
            /** Hit Lines */
            hit_lines: number;
        };
        /**
         * SongDetail
         * @description A playable song with its synced lyrics.
         *
         *     Attributes:
         *         analysis_id: Id of the current analysis; play sessions are bound to it.
         *         analysis_version: Version number of the current analysis.
         *         lines: Lyric lines with timed words (the pitch curve is served apart).
         */
        SongDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Artist */
            artist: string;
            /** Language */
            language: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Line Count */
            line_count: number;
            /** Reprocessing */
            reprocessing: boolean;
            /**
             * Analysis Id
             * Format: uuid
             */
            analysis_id: string;
            /** Analysis Version */
            analysis_version: number;
            /** Lines */
            lines: components["schemas"]["LyricLine"][];
        };
        /**
         * SongPage
         * @description A page of catalog songs.
         *
         *     Attributes:
         *         items: Songs in this page, ordered by title.
         *         total: Songs matching the query across all pages.
         *         limit: Max songs per page requested.
         *         offset: Songs skipped before this page.
         */
        SongPage: {
            /** Items */
            items: components["schemas"]["SongSummary"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * SongRegistration
         * @description Result of registering a song.
         *
         *     Attributes:
         *         song_id: Id of the new song.
         *         job_id: Id of the ingestion job created for it.
         *         status: Status of the song.
         *         stage: Stage of the ingestion job.
         *         separation_preset: Preset that will be used to split the song.
         */
        SongRegistration: {
            /**
             * Song Id
             * Format: uuid
             */
            song_id: string;
            /**
             * Job Id
             * Format: uuid
             */
            job_id: string;
            status: components["schemas"]["SongStatus"];
            stage: components["schemas"]["IngestionStage"];
            separation_preset: components["schemas"]["SeparationPreset"];
        };
        /**
         * SongStatus
         * @description Lifecycle of a song in the catalog.
         * @enum {string}
         */
        SongStatus: "pending" | "processing" | "ready" | "failed";
        /**
         * SongStatusReport
         * @description Ingestion status of a song, for administrators.
         *
         *     Attributes:
         *         song_id: Song id.
         *         title: Song title.
         *         artist: Performing artist.
         *         status: Lifecycle status of the song.
         *         error_message: Last failure reason, if any.
         *         separation_preset: Preset used to split vocals and instrumental.
         *         has_lyrics: Whether official lyrics are loaded.
         *         duration_ms: Duration, once known.
         *         current_analysis_version: Version that is playable, if any.
         *         latest_job: Most recent ingestion job, if any.
         */
        SongStatusReport: {
            /**
             * Song Id
             * Format: uuid
             */
            song_id: string;
            /** Title */
            title: string;
            /** Artist */
            artist: string;
            status: components["schemas"]["SongStatus"];
            /** Error Message */
            error_message: string | null;
            separation_preset: components["schemas"]["SeparationPreset"];
            /** Has Lyrics */
            has_lyrics: boolean;
            /** Duration Ms */
            duration_ms: number | null;
            /** Current Analysis Version */
            current_analysis_version: number | null;
            latest_job: components["schemas"]["JobReport"] | null;
        };
        /**
         * SongSummary
         * @description A playable song as listed in the catalog.
         *
         *     Attributes:
         *         id: Song id.
         *         title: Song title.
         *         artist: Performing artist.
         *         language: ISO 639-1 code of the lyrics, if known.
         *         duration_ms: Duration of the song.
         *         line_count: Number of lyric lines (scoring units).
         *         reprocessing: True while a newer analysis is being produced; the song
         *             stays playable with its current one.
         */
        SongSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Artist */
            artist: string;
            /** Language */
            language: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Line Count */
            line_count: number;
            /** Reprocessing */
            reprocessing: boolean;
        };
        /**
         * SungPitch
         * @description Pitch the player sang over one line, as stored for later analysis.
         *
         *     Attributes:
         *         hop_ms: Time between frames.
         *         f0_hz: Pitch per frame from the line start, 0 where unvoiced.
         */
        SungPitch: {
            /** Hop Ms */
            hop_ms: number;
            /** F0 Hz */
            f0_hz: number[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Word
         * @description A transcribed word with its timing.
         *
         *     Attributes:
         *         text: The word as transcribed, including attached punctuation.
         *         start_ms: Start time from the beginning of the song.
         *         end_ms: End time (exclusive); greater than ``start_ms``.
         *         probability: Transcriber confidence in [0, 1], if available.
         */
        Word: {
            /** Text */
            text: string;
            /** Start Ms */
            start_ms: number;
            /** End Ms */
            end_ms: number;
            /** Probability */
            probability?: number | null;
        };
        /**
         * WordDiagnostics
         * @description A word with what is known about its timing.
         *
         *     Attributes:
         *         voiced_ratio: Fraction of the word's span where the reference vocals
         *             have voice. Low values on sung words point to lyrics out of sync.
         *         probability: Transcriber confidence, None for official lyrics words
         *             without a transcribed match.
         */
        WordDiagnostics: {
            /** Text */
            text: string;
            /** Start Ms */
            start_ms: number;
            /** End Ms */
            end_ms: number;
            /** Voiced Ratio */
            voiced_ratio: number;
            /** Probability */
            probability: number | null;
        };
        /**
         * ErrorCode
         * @description Machine-readable error codes sent over the WebSocket.
         * @enum {string}
         */
        ErrorCode: "invalid_message" | "unknown_line" | "line_already_scored";
        /**
         * ErrorMessage
         * @description Server -> client: a message could not be processed (connection stays open).
         *
         *     Attributes:
         *         type: Message type.
         *         code: What went wrong.
         *         detail: Human-readable explanation.
         */
        ErrorMessage: {
            /**
             * Type
             * @default error
             * @constant
             */
            type: "error";
            code: components["schemas"]["ErrorCode"];
            /** Detail */
            detail: string;
        };
        /**
         * FinishMessage
         * @description Client -> server: the song is over; compute the totals and close.
         *
         *     Attributes:
         *         type: Message type.
         */
        FinishMessage: {
            /**
             * Type
             * @constant
             */
            type: "finish";
        };
        /**
         * LinePitchMessage
         * @description Client -> server: the pitch the player sang over one line.
         *
         *     Attributes:
         *         type: Message type.
         *         line_index: Line that was sung.
         *         hop_ms: Time between pitch frames.
         *         f0_hz: Pitch per frame in Hz, from the line start (0 = no voice). Send a
         *             little more than the line (~300 ms) for latency compensation.
         */
        LinePitchMessage: {
            /**
             * Type
             * @constant
             */
            type: "line_pitch";
            /** Line Index */
            line_index: number;
            /** Hop Ms */
            hop_ms: number;
            /** F0 Hz */
            f0_hz: number[];
        };
        /**
         * LineScoreMessage
         * @description Server -> client: the score of a sung line.
         *
         *     Attributes:
         *         type: Message type.
         *         line_index: Line that was scored.
         *         scorable: False when the line has too little singing to judge.
         *         score: 0-100, None if not scorable.
         *         accuracy: Fraction of in-tune frames, None if not scorable.
         *         hit: Whether the line counts towards the streak.
         *         streak: Consecutive hits ending at this line.
         */
        LineScoreMessage: {
            /**
             * Type
             * @default line_score
             * @constant
             */
            type: "line_score";
            /** Line Index */
            line_index: number;
            /** Scorable */
            scorable: boolean;
            /** Score */
            score: number | null;
            /** Accuracy */
            accuracy: number | null;
            /** Hit */
            hit: boolean;
            /** Streak */
            streak: number;
        };
        /**
         * ReadyMessage
         * @description Server -> client: the session is open and ready to score lines.
         *
         *     Attributes:
         *         type: Message type.
         *         session_id: Id of the session.
         *         analysis_id: Analysis the lines are scored against.
         *         line_count: Number of lyric lines.
         *         scored_lines: Lines already scored (when reconnecting).
         */
        ReadyMessage: {
            /**
             * Type
             * @default ready
             * @constant
             */
            type: "ready";
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Analysis Id
             * Format: uuid
             */
            analysis_id: string;
            /** Line Count */
            line_count: number;
            /** Scored Lines */
            scored_lines: number[];
        };
        /**
         * SessionSummaryMessage
         * @description Server -> client: final totals, sent right before closing.
         *
         *     Attributes:
         *         type: Message type.
         */
        SessionSummaryMessage: {
            /** Total Score */
            total_score: number | null;
            /** Accuracy */
            accuracy: number | null;
            /** Best Streak */
            best_streak: number;
            /** Scored Lines */
            scored_lines: number;
            /** Hit Lines */
            hit_lines: number;
            /**
             * Type
             * @default session_summary
             * @constant
             */
            type: "session_summary";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_songs_songs_get: {
        parameters: {
            query?: {
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_song_songs__song_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                song_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongDetail"];
                };
            };
            /** @description Song not available */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_instrumental_songs__song_id__instrumental_get: {
        parameters: {
            query?: never;
            header?: {
                Range?: string | null;
            };
            path: {
                song_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Requested byte range */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Song not available */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Range out of file */
            416: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pitch_songs__song_id__pitch_get: {
        parameters: {
            query?: {
                line?: number | null;
            };
            header?: never;
            path: {
                song_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PitchResponse"];
                };
            };
            /** @description Song or line not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionCreated"];
                };
            };
            /** @description Song not available */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_results_sessions__session_id__results_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResults"];
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_line_analysis_sessions__session_id__lines__line_index__analysis_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                line_index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinePractice"];
                };
            };
            /** @description Session or line not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_song_admin_songs_post: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_song_admin_songs_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongRegistration"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description File too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not an audio file */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Queue or admin down */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    set_song_lyrics_admin_songs__song_id__lyrics_put: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path: {
                song_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LyricsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LyricsSummary"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Song not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_song_status_admin_songs__song_id__status_get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path: {
                song_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SongStatusReport"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Song not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_line_diagnostics_admin_sessions__session_id__lines__line_index__debug_get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string | null;
            };
            path: {
                session_id: string;
                line_index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LineDiagnostics"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Session or line not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
